### ISSUE TITLE
Envío de datos

### ISSUE THREAD

**Issue by jesusmartinoza** [energy-berry/FW-ESP32#5]
Desarrollo del envío de datos por medio de BLE a la aplicación.

**Comment by Kazhuru** [comment]
Se utilizo para probar el correcto uso del ADC por medio de un potenciometro conectado a VCC y GND donde su salida, es leida por el modulo en elPin 34 predefinido como salida si el ADC activado. 
![img_20190211_164326731](https://user-images.githubusercontent.com/17280833/52599277-cecd4880-2e1d-11e9-95a5-79df757e1899.jpg) 

Fue utilizada la aplicación RFC connect para el envio y recibo de datos del modulo al celular, en esta captura se puede ver como se mando desde el celular un "hola mundo <3" y despues se hicieron 3 lecturas a la señal analogica del potenciometro.
![screenshot_20190211-164718](https://user-images.githubusercontent.com/17280833/52599302-d8ef4700-2e1d-11e9-96ff-8390426b98ac.png)

Aqui al igual que la pantalla de log en la aplicacion se desmuestra en tiempo real la comunicacion Bidireccional entre nuestro dispositivo movil y el modulo ESP32
![img_20190211_164706345](https://user-images.githubusercontent.com/17280833/52599309-df7dbe80-2e1d-11e9-8408-a35d35fc95cc.jpg)
